### ISSUE TITLE
website has broken links to config.yml.example

### ISSUE THREAD

**Issue by tv42** [coredhcp/coredhcp#128]
https://coredhcp.io/README.md

```
<p>For more complex examples, like how to listen on specific interfaces and configure other plugins, see <a href="cmds/coredhcp/config.yml.example">config.yml.example</a>.</p>
```
```
<p>Once you have a working configuration in <code>config.yml</code> (see <a href="cmds/coredhcp/config.yml.example">config.yml.example</a>), you can build and run the server:</p>
```

Both links are broken. Github repo README has a working link to https://github.com/coredhcp/coredhcp/blob/master/cmds/coredhcp/config.yml.example

**Comment by tv42** [comment]
Also broken: website link to plugins https://coredhcp.io/plugins/ is 404, the generator https://coredhcp.io/cmds/coredhcp-generator/ is 404.

**Comment by insomniacslk** [comment]
Thanks for reporting! The current website does some silly translation of URLs, but in reality we should better use GitHub Pages for this. Let me fix the URLs first then I'll move to github pages

**Comment by insomniacslk** [comment]
This should be fixed now

**Comment by insomniacslk** [comment]
@tv42 please let me know if you see any more broken links

**Comment by tv42** [comment]
Still broken: "Then try it with the local test client, that is located under cmds/client/:" links to https://coredhcp.io/cmds/client which is 404.

**Comment by insomniacslk** [comment]
oh the issue there is that it doesn't end with a `/`, in fact https://coredhcp.io/cmds/client/ works . With the current system it's not possible to distinguish the two cases, I will migrate to github pages ASAP as it is the clean solution

**Comment by insomniacslk** [comment]
Now https://coredhcp.io/ is fully pointing to GitHub Pages, and the links should be all accessible

**Comment by tv42** [comment]
Now the config.yml.example link to https://coredhcp.io/cmds/coredhcp/config.yml.example triggers a download!

Links to 404s: 
https://coredhcp.io/cmds/coredhcp/
https://coredhcp.io/cmds/client/
https://coredhcp.io/plugins/
https://coredhcp.io/plugins/example/

**Comment by insomniacslk** [comment]
wow. Sorry about that, something must have gone wrong when I had set up the custom domain redirection on GitHub. Looking now

**Comment by insomniacslk** [comment]
interestingly I also get the download prompt if I open coredhcp.io from my browser in non-incognito. In incognito, everything works just fine. With curl too

**Comment by insomniacslk** [comment]
> interestingly I also get the download prompt if I open coredhcp.io from my browser in non-incognito. In incognito, everything works just fine. With curl too

This was due to broken cached data on my side. Now looking at the other issues

**Comment by insomniacslk** [comment]
Oh, I think I found an explanation. GitHub Pages expects a README.md when passing a path to a directory, so this works for cmds/coredhcp-generator (because it contains a README.md) but not with cmds/clients and others.

And for config.yaml.example it returns `content-type: application/octet-stream` as content-type, because I believe that GitHub Pages automatically tries to guess the content type

**Comment by insomniacslk** [comment]
The same thing doesn't happen when browsing from the repository on github.com. I wonder if this is "working as intended", and in that case we need a workaround. For README.md that's pretty easy, for the content-type I am not so sure

**Comment by gaby** [comment]
@insomniacslk The website is broken again, a lot of the URL's are returning 404 including the Plugins page.

**Comment by insomniacslk** [comment]
I don't get notifications for this stuff for some reason.. anyway, the website has been migrated long time ago to GitHub Pages, so this should be solved for good. Please reopen if you still find some issues. Thanks!
